site_name: AEA Storj File Uploader
site_url: ''
site_description: ''
site_author: ''

theme:
  name: material
#  logo:
#    icon: code
#  feature:
#    tabs: true  

nav:
  - Index: 'index.md'
  - Strategy Flow: 'strategy_flow.md'
  - Prerequisites: 'prerequisites.md'
  - Setup: 'setup.md'
  - Demo: 'demo.md'
  - Gitlab CI: 'ci.md'

plugins: 
  - mkdocs-video

markdown_extensions: []
