agent_name: storj_agent
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.1.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/storj_file_transfer:0.1.0
contracts: []
protocols:
- eightballer/file_storage:0.1.0
- fetchai/default:1.0.0
- fetchai/signing:1.0.0
- fetchai/state_update:1.0.0
skills:
- eightballer/storj_file_uploader:0.1.0
default_ledger: ethereum
required_ledgers:
- fetchai
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths:
  ethereum: ethereum_private_key.txt
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
default_connection: null
---
public_id: eightballer/storj_file_transfer:0.1.0
type: connection
config:
  target_skill_id: eightballer/storg_file_transfer:0.1.0
  storj_creds:
    aws_access_key_id: jx7bgg74ceog3eznrovaiqcy23sa
    aws_secret_access_key: j2wulv3drlgrt5apjr2csc5lmkzyqpqakgzuoc63fn6wedxmnu2ng
    endpoint_url: https://gateway.eu1.storjshare.io
